services:
  #neko-firefox:
  #  image: "ghcr.io/m1k1o/neko/firefox:latest"
  #  restart: "unless-stopped"
  #  shm_size: "2gb"
  #  ports:
  #    - "8080:8080"
  #    - "52000-52100:52000-52100/udp"
  #  environment:
  #    NEKO_DESKTOP_SCREEN: 1920x1080@30
  #    NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
  #    NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
  #    NEKO_WEBRTC_EPR: 52000-52100
  #    NEKO_WEBRTC_ICELITE: 1

  neko-chromium:
    image: "ghcr.io/m1k1o/neko/chromium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    ports:
      - "8080:8080"
      - "9223:9223"
      - "56000-56100:56000-56100/udp"
    volumes:
      - ".docker/chrome:/home/neko/.config/chromium"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_EPR: 56000-56100
      NEKO_WEBRTC_NAT1TO1: 127.0.0.1
      NEKO_WEBRTC_ICELITE: 1
      NEKO_DESKTOP_UNMINIMIZE: true
      NEKO_DESKTOP_UPLOAD_DROP: true
